In [2]:
import array

L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
import numpy as np

np.array([range(i, i + 3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [5]:
np.full((3,5), 1.2)

array([[1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2],
       [1.2, 1.2, 1.2, 1.2, 1.2]])

In [7]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [9]:
np.linspace(0, 5, 3)

array([0. , 2.5, 5. ])

In [12]:
np.random.random((3,3))

array([[0.61253045, 0.5515301 , 0.87749637],
       [0.61062104, 0.98102567, 0.91164022],
       [0.34065783, 0.65903666, 0.42374401]])

In [13]:
np.random.normal(0, 1, (3,3))

array([[ 2.03860629,  0.06179472,  1.02229882],
       [ 0.10173346,  0.42840333, -1.61795808],
       [-0.11504405,  1.76668308,  0.95446087]])

In [14]:
np.random.randint(0, 10, (2,3))

array([[4, 3, 5],
       [4, 4, 2]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.empty(4)

array([2.57545328e+214, 3.62604506e-043, 5.94484328e-096, 3.58467710e-038])

In [20]:
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [21]:
x3

array([[[4, 9, 9, 3, 5],
        [5, 5, 1, 6, 3],
        [5, 6, 8, 5, 3],
        [2, 0, 8, 3, 7]],

       [[1, 8, 0, 8, 5],
        [3, 0, 1, 8, 3],
        [3, 2, 3, 3, 0],
        [7, 1, 4, 6, 1]],

       [[6, 2, 6, 8, 2],
        [6, 5, 8, 2, 7],
        [9, 3, 6, 0, 4],
        [3, 4, 5, 7, 0]]])

In [23]:
x3.itemsize

4

In [25]:
x3.size

60

In [24]:
x3.nbytes

240

In [26]:
x2

array([[2, 3, 5, 8],
       [5, 5, 3, 0],
       [8, 3, 1, 3]])

In [27]:
x4 = x2.copy()

In [30]:
x4.reshape(4,3)

array([[2, 3, 5],
       [8, 5, 5],
       [3, 0, 8],
       [3, 1, 3]])

In [35]:
x4[np.newaxis, :]

array([[[2, 3, 5, 8],
        [5, 5, 3, 0],
        [8, 3, 1, 3]]])

In [36]:
x4[:, np.newaxis]

array([[[2, 3, 5, 8]],

       [[5, 5, 3, 0]],

       [[8, 3, 1, 3]]])