In [1]:
import pandas as pd
import numpy as np

In [2]:
for dtype in ['object', 'int']:
    print('dtype = ', dtype)
    %timeit np.arange(1E6, dtype = dtype).sum()
    print()

dtype =  object
145 ms ± 12.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

dtype =  int
4.62 ms ± 260 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [3]:
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5],
                  [np.nan, 4, 6]])

In [4]:
df.dropna(axis = 1)

2
0  2
1  5
2  6

In [5]:
data = pd.Series([1, np.nan, 9, None, 6], index = list('abcde'))
data

a    1.0
b    NaN
c    9.0
d    NaN
e    6.0
dtype: float64

In [6]:
data.fillna(method = 'bfill')

a    1.0
b    9.0
c    9.0
d    6.0
e    6.0
dtype: float64

In [7]:
index = [('California', 2000), ('California', 2010), ('New York', 2000), ('New York', 2010), ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

pop = pd.Series(populations, index = index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [17]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [9]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [10]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [11]:
pop_df = pop.unstack()
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [12]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [14]:
pop_df = pd.DataFrame({'total': pop, 'under18': [9267089, 9284094, 4687374, 4318033, 5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [15]:
np.random.rand(4,2)

array([[0.44742732, 0.37903856],
       [0.09978143, 0.5065948 ],
       [0.81303225, 0.03794811],
       [0.24280117, 0.74732641]])

In [20]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [21]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [22]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [27]:
pop.index.names = ['state', 'year']
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [28]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]], names = ['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']], names = ['subject', 'type'])

In [30]:
data = np.round(np.random.randn(4, 6), 1)
data

array([[ 0.4,  1.5,  1.4,  0.6,  1.2,  0.5],
       [ 1.5,  0.1, -0.5,  0.1, -1.2, -0.1],
       [ 1.5,  0.7, -0.4, -0.3, -0.6,  2.2],
       [-0.6,  1.1,  0.3, -0.3, -2.1, -1. ]])

In [31]:
data[:, ::2] *= 10
data

array([[  4. ,   1.5,  14. ,   0.6,  12. ,   0.5],
       [ 15. ,   0.1,  -5. ,   0.1, -12. ,  -0.1],
       [ 15. ,   0.7,  -4. ,  -0.3,  -6. ,   2.2],
       [ -6. ,   1.1,   3. ,  -0.3, -21. ,  -1. ]])

In [32]:
data += 37
data

array([[41. , 38.5, 51. , 37.6, 49. , 37.5],
       [52. , 37.1, 32. , 37.1, 25. , 36.9],
       [52. , 37.7, 33. , 36.7, 31. , 39.2],
       [31. , 38.1, 40. , 36.7, 16. , 36. ]])

In [33]:
health_data = pd.DataFrame(data, index = index, columns = columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      41.0  38.5  51.0  37.6  49.0  37.5
     2      52.0  37.1  32.0  37.1  25.0  36.9
2014 1      52.0  37.7  33.0  36.7  31.0  39.2
     2      31.0  38.1  40.0  36.7  16.0  36.0

In [38]:
health_data.loc[2013]

subject   Bob       Guido         Sue      
type       HR  Temp    HR  Temp    HR  Temp
visit                                      
1        41.0  38.5  51.0  37.6  49.0  37.5
2        52.0  37.1  32.0  37.1  25.0  36.9

In [43]:
health_data['Bob']

type          HR  Temp
year visit            
2013 1      41.0  38.5
     2      52.0  37.1
2014 1      52.0  37.7
     2      31.0  38.1